kind: Deployment
apiVersion: apps/v1
metadata:
  name: app02
spec:
  template:
    metadata:
      labels:
        app: app02
    spec:
      containers:
      - name: app02
        image: 363412468025.dkr.ecr.us-east-2.amazonaws.com/app02:latest
  selector:
    matchLabels:
      app: app02
---
kind: Service
apiVersion: v1
metadata:
  name: app02
spec:
  type: LoadBalancer
  selector:
    app: app02
  ports:
  - name: http
    port: 5002
    targetPort: 3002
